# NumPy Exercises

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [50]:
import numpy as np

#### Create an array of 10 zeros

In [51]:
arr1 = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0])

#### Create an array of 10 ones

In [52]:
arr2 = np.array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [53]:
arr3 = np.full(10, 5)

#### Create an array of the integers from 10 to 50

In [54]:
arr4 = np.arange(10, 51)

#### Create an array of all the even integers from 10 to 50

In [55]:
arr5 = np.arange(10, 51, 20)

#### Create a 3x3 matrix with values ranging from 0 to 8

In [56]:
arr7 = np.array([[0, 1, 2 ],
                 [3, 4, 5 ],
                 [6, 7, 8 ]])


#### Create a 3x3 identity matrix

In [57]:
arr8 = np.array([[1., 0., 0.],
                 [0., 1., 0.],
                 [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [58]:
from numpy import random
x = random.rand()

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [59]:
arr10 = np.random.uniform(-2, 2, size=25)

#### Create the following matrix:

In [60]:
arr11 = np.linspace(0.01, 1.00, 100).reshape(10, 10)

#### Create an array of 20 linearly spaced points between 0 and 1:

In [61]:
arr12 = np.round(np.linspace(0.00, 1.00, 20), 8).reshape(4, 5)

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [62]:
arr9 = np.array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [63]:
arr9[2:5, 0:5]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [64]:
arr9[3, -1]

np.int64(20)

In [65]:
arr9[0:3, 1:2]

array([[ 2],
       [ 7],
       [12]])

In [66]:
arr9[4, 0:5]

array([21, 22, 23, 24, 25])

In [67]:
arr9[3:5, 0:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

# Great Job!